name = "hiro"
license = "MIT"
licenselink = "https://github.com/roykn/hiro/blob/main/LICENSE"
description = "A simple, dark Hugo theme for personal blogs."
homepage = "http://example.com/"
tags = ["simple", "dark", "blog", "clean", "personal"]
features = ["responsive"]
min_version = "0.41"

[author]
  name = "Roy Knäbel"
  homepage = "https://github.com/roykn"
